name: Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to deploy (e.g. 123)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Проверяем существование докер образа
        run: |
          docker login --username iam --password-stdin cr.yandex <<< "${{ secrets.YAN_TOKEN }}"
          docker pull cr.yandex/crpuv7mc1hbevup1qva6/app:${{ inputs.version }}_latest || exit 1

      - name: Деплоим
        uses: appleboy/ssh-action@v1
        with:
          host: 158.160.63.206
          username: basic-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:3000 \
              -e NODE_ENV=production \
              cr.yandex/crpuv7mc1hbevup1qva6/app:${{ inputs.version }}_latest

      - name: Находим issue релиза
        id: find-issue
        uses: peter-evans/find-issue@v2
        with:
          state: open
          labels: release
          title-contains: "Release v${{ inputs.version }}"

      - name: Добавляем деплой комментарий
        if: steps.find-issue.outputs.issue-number != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.find-issue.outputs.issue-number }}
          body: |
            **Deployed to Production**  
            - Version: ${{ inputs.version }}  
            - Deployed by: ${{ github.actor }}  
            - Date: $(date -u +'%Y-%m-%d %H:%M:%S')  
            - Image: `cr.yandex/crpuv7mc1hbevup1qva6/app:${{ inputs.version }}_latest`